defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

task:
  project_name: YOLO11n
  task_name: Train on COCO8
  task_type: optimizer
  reuse_last_task_id: False

dataset:
  project: YOLO11
  name: sample
  version: 1.0.0
  output_dir: ./data

training:
  model_name: yolo11n
  model_weights: yolo11n.pt

yolo_args:
  data:  yolo.yaml
  epochs: 10
  imgsz: 416
  batch: 2
  device: 0
  workers: 2
hydra:
  run:
    dir: .